import random
hin_to_eng = [
    {"hindi": "और", "english": "and"},
    {"hindi": "है", "english": "is"},
    {"hindi": "यह", "english": "this"},
    {"hindi": "वह", "english": "that"},
    {"hindi": "के", "english": "of"},
    {"hindi": "में", "english": "in"},
    {"hindi": "से", "english": "from"},
    {"hindi": "को", "english": "to"},
    {"hindi": "पर", "english": "on"},
    {"hindi": "हैं", "english": "are"},
    {"hindi": "एक", "english": "one"},
    {"hindi": "नहीं", "english": "not"},
    {"hindi": "के लिए", "english": "for"},
    {"hindi": "था", "english": "was"},
    {"hindi": "हुआ", "english": "happened"},
    {"hindi": "क्या", "english": "what"},
    {"hindi": "कौन", "english": "who"},
    {"hindi": "कब", "english": "when"},
    {"hindi": "क्यों", "english": "why"},
    {"hindi": "कैसे", "english": "how"},
    {"hindi": "का", "english": "of"},
    {"hindi": "पास", "english": "near"},
    {"hindi": "हम", "english": "we"},
    {"hindi": "आप", "english": "you"},
    {"hindi": "वे", "english": "they"},
    {"hindi": "उसे", "english": "him/her"},
    {"hindi": "उसके", "english": "his/her"},
    {"hindi": "इसे", "english": "this"},
    {"hindi": "इनके", "english": "their"},
    {"hindi": "जो", "english": "who/which"},
    {"hindi": "कोई", "english": "any"},
    {"hindi": "कुछ", "english": "some"},
    {"hindi": "अभी", "english": "now"},
    {"hindi": "तो", "english": "so"},
    {"hindi": "बाद", "english": "after"},
    {"hindi": "फिर", "english": "then"},
    {"hindi": "या", "english": "or"},
    {"hindi": "अगर", "english": "if"},
    {"hindi": "हर", "english": "every"},
    {"hindi": "किसी", "english": "someone"},
    {"hindi": "सब", "english": "all"},
    {"hindi": "चाहिए", "english": "should"},
    {"hindi": "देखा", "english": "saw"},
    {"hindi": "किया", "english": "did"},
    {"hindi": "बनाया", "english": "made"},
    {"hindi": "बोलो", "english": "speak"},
    {"hindi": "लिया", "english": "took"},
    {"hindi": "दिया", "english": "gave"},
    {"hindi": "चला", "english": "walked"},
    {"hindi": "आया", "english": "came"},
    {"hindi": "गया", "english": "went"},
    {"hindi": "बैठा", "english": "sat"},
    {"hindi": "खड़ा", "english": "stood"},
    {"hindi": "सुना", "english": "heard"},
    {"hindi": "जाना", "english": "to go"},
    {"hindi": "खेल", "english": "play"},
    {"hindi": "पढ़ा", "english": "read"},
    {"hindi": "लिखा", "english": "write"},
    {"hindi": "खा", "english": "eat"},
    {"hindi": "पी", "english": "drink"},
    {"hindi": "सो", "english": "sleep"},
    {"hindi": "उठा", "english": "wake up"},
    {"hindi": "बताया", "english": "told"},
    {"hindi": "सोचा", "english": "thought"},
    {"hindi": "समझा", "english": "understood"},
    {"hindi": "मिला", "english": "met"},
    {"hindi": "खरीदा", "english": "bought"},
    {"hindi": "बेचा", "english": "sold"},
    {"hindi": "सीखा", "english": "learned"},
    {"hindi": "पाया", "english": "found"},
    {"hindi": "रखा", "english": "kept"},
    {"hindi": "छोड़ा", "english": "left"},
    {"hindi": "लाया", "english": "brought"},
    {"hindi": "दिखाया", "english": "showed"},
    {"hindi": "पूछा", "english": "asked"},
    {"hindi": "पहुंचा", "english": "reached"},
    {"hindi": "खोला", "english": "opened"},
    {"hindi": "बंद", "english": "close"},
    {"hindi": "जीता", "english": "won"},
    {"hindi": "हारा", "english": "lost"},
    {"hindi": "कहा", "english": "said"},
    {"hindi": "करो", "english": "do"},
    {"hindi": "रहो", "english": "stay"},
    {"hindi": "आओ", "english": "come"},
    {"hindi": "जाओ", "english": "go"},
    {"hindi": "बोल", "english": "speak"},
    {"hindi": "चलो", "english": "let's go"},
    {"hindi": "रुको", "english": "stop"},
    {"hindi": "पकड़ो", "english": "catch"},
    {"hindi": "छोड़ो", "english": "leave"},
    {"hindi": "दिखाओ", "english": "show"},
    {"hindi": "लाओ", "english": "bring"},
    {"hindi": "बचाओ", "english": "save"},
    {"hindi": "ढूंढो", "english": "search"},
    {"hindi": "पढ़ाई", "english": "study"},
    {"hindi": "लड़ाई", "english": "fight"},
    {"hindi": "काम", "english": "work"},
    {"hindi": "प्यार", "english": "love"},
    {"hindi": "दोस्ती", "english": "friendship"},
    {"hindi": "खुशी", "english": "happiness"},
    {"hindi": "दुख", "english": "sadness"},
    {"hindi": "शांति", "english": "peace"}
]

def main():
    print("Challenge YourSelf with Translation")
    score = 0
    random.shuffle(hin_to_eng)
    for word in hin_to_eng:
        correct_word = word['english']
        print(f"What is English word for {word['hindi']} ?")
        usr_in = input("Your answer: ").strip().lower()
        if usr_in == correct_word:
            score+=1
            print(score)
        else:
            print(f"Idiot! Wrong Word. Correct word is {correct_word}")

        

main()